version: '3.8'
services:
    web:
        build: .
        ports:
             - "5000:5000"
        environment:
             - MONGODB_URI=mongodb://mongo:27017/grocerylist
        depends_on:
            - mongo

    mongo:
        image: mongo:6.0
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data: